language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y monodevelop mono-utils
  - sudo apt-get install -y mono-gmcs 

script: ./gradlew unittest -info -debug

branches:
    only:
        - denis
